---
title: "Untitled"
format: scidata-pdf
---

```{r setup}
#| include: false

# Install packages (if required)
if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse,terra,sf,giscoR,scico,cowplot,kableExtra,scales)
terraOptions(progress=0,memfrac=0.9)

ch_pal = c("#8400a8","#ff00c5","#e8e8e8")

knitr::knit_hooks$set(inline = function(x) {
  prettyNum(x, big.mark=",",digits=4)
})

```

```{r import-rasters}
#| include: false

ch2023_areas = data.frame(
  value=c(0,1,10),
  area=c(441808946,16616792,51639884)
)

features_table = read.csv("features_table.csv",check.names=F)

```

```{r ch-coverage-table-pdf}
#| echo: false
#| tbl-cap: "Areas and percentage coverage of each Critical Habitat category in 2018 and 2023 across Areas Beyond National Jurisdiction (ABNJ), Economic Exclusion Zones (EEZ) and Land."

wrld_ch_areas = read.csv("wrld_ch_areas.csv",check.names = F) |>
  group_by(type) |>
  summarise(across(starts_with(c("2018","2023")),~sum(.x,na.rm=TRUE)/1000000))

wrld_ch_pct = wrld_ch_areas |>
  reframe(across(2:7,~label_percent(accuracy=.2)(.x/sum(.x)))) |>
  rename_with(~paste0(.x,"_pct"))

wrld_ch_areas_pct = cbind(wrld_ch_areas,wrld_ch_pct) %>% 
  select(type,sort(names(.)))

names(wrld_ch_areas_pct) <- NULL

kable(wrld_ch_areas_pct,
      format.args = list(digits=2,big.mark=","),
      format="latex",
      booktabs=T,
      longtable=T) |>
  add_header_above(header=c("Domain"=1,"Likely"=2,"Potential"=2,"Unclassified"=2,
                           "Likely"=2,"Potential"=2,"Unclassified"=2)) |>
  add_header_above(header=c(" "=1,"2018"=6,"2023"=6)) |>
  column_spec(1,width="1cm") |>
  column_spec(c(3,5,7,9,11,13),width="1cm") |>
  column_spec(c(2,4,6,8,10,12),width="0.5cm") |>
  kable_styling(font_size=8) |>
  footnote(general="Areas in million $km^2$.",escape=F)

```