# Update to the global Critical Habitat screening layer

The process for compiling the complete Critical Habitat layers comprises three main steps, split across six separate scripts.

The most up-to-date layers can be found on the [UN Environment Programme World Conservation Monitoring Centre data portal](https://data-gis.unep-wcmc.org/portal/home/).

While some of the input data can be prepared using the scripts provided here through a direct interface with the UNEP-WCMC data portal, many input datasets cannot be provided here and must be sought, with permission, from their respective owners.

## 1 Data preprocessing

### 1.1 Red_List_Preprocessing.R

Queries the IUCN Red List to produce four input datasets for the analysis: CR, EN, VU species, and Great Apes. The script includes code, currently commented out, that can add a desired buffer to these data.

### 1.2 Data_Preprocessing_Raster.R

Pre-processes any input data only available in raster format. This script includes the processing of extremely high resolution tropical moist forest and mangrove data, both of which can take days to complete.

### 1.3 Data_Preprocessing_Vector.R

The main pre-processing script: pre-processes all vector input data. Some datasets, e.g. warm-water coral reefs, are extremely detailed and take a substantial time to complete.

> N.B. At this stage, the lookup table, `lookup.csv`, needs to be manually edited in Excel or similar to include all features for which **data exist**. For example, at the moment, many KBA criteria do not have any sites triggering them. So while a criterion may align with the definition of Critical Habitat, the pre-processing scripts will not output any data for them so they need removed from the lookup.

## 2 Creating Critical Habitat layers

### 2 Create_Drill_Down_Critical_Habitat_Raster_Layer.R

Combines all standardised input data from 1.1, 1.2, and 1.3 to produce the finished drill down raster layer with accompanying attribute table in WGS 84.

## 3 Post-processing

### 3.1 Create_Basic_Critical_Habitat_Raster_Layers.R

"Flattens" the drill down raster layer produced in 2 to only contain one attribute: whether a cell is "Likely" Critical Habitat (10), "Potential" (1), or "Unclassified" (0).

### 3.2 Create_Drill_Down_Polygons.R

Polygonises the drill down raster layer produced in 2 and reorders the variables to be more user-friendly in a way not possible with raster data.